# Generated by Django 6.0.5 on 2026-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='group_instruction',
            field=models.TextField(blank=True, help_text="e.g. 'Complete the notes below. Write ONE WORD AND/OR A NUMBER for each answer.'"),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='group_title',
            field=models.CharField(blank=True, help_text="e.g. 'Questions 1-10' — same value groups questions together.", max_length=200),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='question_text',
            field=models.TextField(help_text='For gap_fill inside notes, use ___ where the blank should appear.'),
        ),
    ]
