# Generated by Django 6.0.5 on 2026-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Teachers can log into /admin to add tests and view results, but cannot manage users or site settings.'),
        ),
    ]
